#全局端口定义server:
# 全局字符集设置
spring:
  http:
    encoding:
      force: true
      charset: utf-8
      enabled: true
  aop:
    proxy-target-class: true
  profiles:
    active: prod
server:
  tomcat:
    uri-encoding: utf-8

